import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const outDir = path.join(root, "public", "cars");
const headers = { "User-Agent": "SCEFleetImageFetch/1.0 (local car rental site build)", Accept: "application/json,image/*" };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const jobs = [
  ["venue-2025", "Hyundai Venue SUV"],
  ["nexon", "Tata Nexon"],
  ["punch-2024", "Tata Punch"],
  ["curvv-2024", "Tata Curvv"],
  ["swift", "Maruti Suzuki Swift"],
  ["baleno-2024", "Maruti Suzuki Baleno"],
  ["fronx-grey-2025", "Maruti Suzuki Fronx"],
  ["grand-vitara-2024", "Maruti Grand Vitara"],
  ["scorpio-n", "Mahindra Scorpio-N"],
  ["thar-3-door", "Mahindra Thar"],
  ["xuv700", "Mahindra XUV700"],
  ["seltos-2024", "Kia Seltos"],
  ["exter", "Hyundai Exter"],
  ["xuv-3xo", "Mahindra XUV 3XO"],
];

function usable(page) {
  const info = page.imageinfo?.[0];
  if (!info?.thumburl) return null;
  const title = (page.title || "").toLowerCase();
  if (["logo", "icon", "interior", "engine", "diagram", "map"].some((w) => title.includes(w))) return null;
  return info.thumburl;
}

async function search(query) {
  const url = new URL("https://commons.wikimedia.org/w/api.php");
  url.searchParams.set("action", "query");
  url.searchParams.set("format", "json");
  url.searchParams.set("generator", "search");
  url.searchParams.set("gsrsearch", query);
  url.searchParams.set("gsrnamespace", "6");
  url.searchParams.set("gsrlimit", "6");
  url.searchParams.set("prop", "imageinfo");
  url.searchParams.set("iiprop", "url|mime");
  url.searchParams.set("iiurlwidth", "1400");
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(String(res.status));
  const data = await res.json();
  const pages = Object.values(data.query?.pages ?? {});
  for (const page of pages) {
    const src = usable(page);
    if (src) return { src, title: page.title };
  }
  return null;
}

await mkdir(outDir, { recursive: true });
const images = {};
for (const [slug, query] of jobs) {
  try {
    const hit = await search(query);
    if (!hit) {
      console.log("MISS", slug);
    } else {
      const res = await fetch(hit.src, { headers });
      if (!res.ok) console.log("FAIL", slug, res.status);
      else {
        const buf = Buffer.from(await res.arrayBuffer());
        const ext = (res.headers.get("content-type") || "").includes("png") ? "png" : "jpg";
        await writeFile(path.join(outDir, `${slug}.${ext}`), buf);
        images[slug] = `/cars/${slug}.${ext}`;
        console.log("OK", slug, hit.title);
      }
    }
  } catch (error) {
    console.log("ERR", slug, error.message);
  }
  await sleep(700);
}

const share = [
  ["venue-2026", "venue-2025"],
  ["punch-2026", "punch-2024"],
  ["swift-white", "swift"],
  ["baleno-2026", "baleno-2024"],
  ["fronx-white-2026", "fronx-grey-2025"],
  ["scorpio-s11", "scorpio-n"],
  ["scorpio-n-facelift", "scorpio-n"],
  ["thar-roxx", "thar-3-door"],
];
for (const [slug, from] of share) {
  if (images[from]) images[slug] = images[from];
}
images.hero = images["thar-3-door"] || images["xuv700"] || images["scorpio-n"] || "";
images.cta = images["xuv700"] || images.hero || "";
images.hatch = images.swift || "";
images.suv = images["venue-2025"] || images.nexon || "";
images.premium = images["scorpio-n"] || images["xuv700"] || "";

const ts = `/* Generated by scripts/fetch-quick.mjs */\nexport const carImages: Record<string, string> = ${JSON.stringify(images, null, 2)};\n`;
await writeFile(path.join(root, "src", "data", "images.ts"), ts);
console.log("COUNT", Object.keys(images).length);
